// diseaseVideos.ts
// Each disease has curated YouTube search queries that return real educational videos

export interface DiseaseVideo {
  title: string;
  searchQuery: string;   // used to build YouTube search URL
  description: string;
  tags: string[];
}

export interface Disease {
  id: string;
  name: string;
  displayName: string;
  category: string;
  color: string;
  youtubeSearch: string;   // main search term for the embedded YouTube search
  videos: DiseaseVideo[];
}

export const diseases: Disease[] = [
  {
    id: 'acne_rosacea',
    name: 'Acne And Rosacea Photos',
    displayName: 'Acne & Rosacea',
    category: 'Inflammatory',
    color: 'bg-red-500',
    youtubeSearch: 'acne rosacea treatment dermatology',
    videos: [
      { title: 'Acne Causes & Treatment', searchQuery: 'acne causes treatment dermatologist', description: 'Understanding acne formation and effective treatments', tags: ['Treatment', 'Causes'] },
      { title: 'How to Get Rid of Acne', searchQuery: 'how to get rid of acne fast dermatologist tips', description: 'Dermatologist-approved acne removal methods', tags: ['Tips'] },
      { title: 'Rosacea Treatment Guide', searchQuery: 'rosacea treatment skincare routine dermatology', description: 'Managing rosacea symptoms effectively', tags: ['Rosacea', 'Treatment'] },
      { title: 'Acne Skincare Routine', searchQuery: 'best skincare routine acne prone skin', description: 'Daily routine for acne-prone skin', tags: ['Routine'] },
      { title: 'Hormonal Acne', searchQuery: 'hormonal acne treatment causes dermatologist', description: 'Hormonal causes of acne and solutions', tags: ['Hormonal'] },
      { title: 'Acne Scar Treatment', searchQuery: 'acne scar treatment removal dermatology', description: 'How to treat and prevent acne scars', tags: ['Scars'] },
      { title: 'Cystic Acne Guide', searchQuery: 'cystic acne treatment causes dermatologist', description: 'Deep dive into cystic acne management', tags: ['Cystic'] },
      { title: 'Rosacea Triggers', searchQuery: 'rosacea triggers how to avoid flare ups', description: 'Identifying and avoiding rosacea triggers', tags: ['Triggers'] },
      { title: 'Acne Ingredients', searchQuery: 'best ingredients for acne salicylic acid benzoyl peroxide', description: 'Key skincare ingredients for acne', tags: ['Ingredients'] },
      { title: 'Acne Diet Connection', searchQuery: 'diet and acne connection foods to avoid', description: 'How diet affects acne', tags: ['Diet'] },
    ],
  },
  {
    id: 'actinic_keratosis',
    name: 'Actinic Keratosis Basal Cell Carcinoma And Other Malignant Lesions',
    displayName: 'Actinic Keratosis & Skin Cancer',
    category: 'Malignant',
    color: 'bg-gray-700',
    youtubeSearch: 'actinic keratosis basal cell carcinoma skin cancer',
    videos: [
      { title: 'Actinic Keratosis Explained', searchQuery: 'actinic keratosis what is it treatment', description: 'Understanding precancerous skin lesions', tags: ['Precancerous'] },
      { title: 'Basal Cell Carcinoma Signs', searchQuery: 'basal cell carcinoma signs symptoms treatment', description: 'Identifying basal cell carcinoma early', tags: ['Carcinoma'] },
      { title: 'Skin Cancer Prevention', searchQuery: 'skin cancer prevention tips dermatologist', description: 'How to prevent skin cancer', tags: ['Prevention'] },
      { title: 'Skin Self-Examination', searchQuery: 'how to check skin for cancer self exam', description: 'How to examine your skin for cancer signs', tags: ['Self-exam'] },
      { title: 'ABCDE Rule for Skin Cancer', searchQuery: 'ABCDE rule skin cancer melanoma detection', description: 'Using the ABCDE rule to spot cancer', tags: ['Detection'] },
      { title: 'Actinic Keratosis Treatment', searchQuery: 'actinic keratosis treatment cryotherapy', description: 'Treatment options for AK', tags: ['Treatment'] },
      { title: 'Mohs Surgery', searchQuery: 'mohs surgery skin cancer procedure explained', description: 'Understanding Mohs surgery for skin cancer', tags: ['Surgery'] },
      { title: 'Sun Damage & Cancer Risk', searchQuery: 'sun damage skin cancer risk UV radiation', description: 'Link between sun damage and cancer', tags: ['Sun damage'] },
      { title: 'Squamous Cell Carcinoma', searchQuery: 'squamous cell carcinoma skin treatment', description: 'Overview of squamous cell carcinoma', tags: ['SCC'] },
      { title: 'Skin Cancer Staging', searchQuery: 'skin cancer staging treatment options dermatology', description: 'How skin cancer is staged and treated', tags: ['Staging'] },
    ],
  },
  {
    id: 'atopic_dermatitis',
    name: 'Atopic Dermatitis Photos',
    displayName: 'Atopic Dermatitis',
    category: 'Inflammatory',
    color: 'bg-orange-400',
    youtubeSearch: 'atopic dermatitis eczema treatment dermatology',
    videos: [
      { title: 'Atopic Dermatitis Overview', searchQuery: 'atopic dermatitis causes symptoms treatment', description: 'Complete guide to atopic dermatitis', tags: ['Overview'] },
      { title: 'Best Moisturizers for AD', searchQuery: 'best moisturizers atopic dermatitis eczema', description: 'Choosing the right moisturizer', tags: ['Moisturizer'] },
      { title: 'AD in Children', searchQuery: 'atopic dermatitis children baby eczema treatment', description: 'Managing AD in kids', tags: ['Children'] },
      { title: 'AD Triggers', searchQuery: 'atopic dermatitis triggers how to avoid eczema', description: 'Identifying and avoiding triggers', tags: ['Triggers'] },
      { title: 'Topical Steroids for AD', searchQuery: 'topical steroids atopic dermatitis safe use', description: 'Safe use of steroids for AD', tags: ['Steroids'] },
      { title: 'Dupilumab Treatment', searchQuery: 'dupilumab atopic dermatitis biologic treatment', description: 'Biologic treatment for severe AD', tags: ['Biologic'] },
      { title: 'Wet Wrap Therapy', searchQuery: 'wet wrap therapy eczema atopic dermatitis', description: 'Wet wrap technique for flares', tags: ['Wet wrap'] },
      { title: 'AD Skincare Routine', searchQuery: 'skincare routine atopic dermatitis sensitive skin', description: 'Daily routine for AD skin', tags: ['Routine'] },
      { title: 'Diet and AD', searchQuery: 'diet atopic dermatitis food triggers elimination', description: 'Role of diet in AD', tags: ['Diet'] },
      { title: 'New AD Treatments', searchQuery: 'new treatments atopic dermatitis 2024 dermatology', description: 'Latest treatments for AD', tags: ['New treatments'] },
    ],
  },
  {
    id: 'eczema',
    name: 'Eczema Photos',
    displayName: 'Eczema',
    category: 'Inflammatory',
    color: 'bg-orange-500',
    youtubeSearch: 'eczema treatment skincare routine dermatology',
    videos: [
      { title: 'Eczema Complete Guide', searchQuery: 'eczema causes symptoms treatment complete guide', description: 'Everything about eczema', tags: ['Guide'] },
      { title: 'Eczema Skincare Routine', searchQuery: 'eczema skincare routine dermatologist recommended', description: 'Daily skincare for eczema', tags: ['Routine'] },
      { title: 'Best Products for Eczema', searchQuery: 'best products eczema moisturizer cream', description: 'Top products for eczema relief', tags: ['Products'] },
      { title: 'Eczema Triggers', searchQuery: 'eczema triggers how to avoid flare ups', description: 'Common triggers to avoid', tags: ['Triggers'] },
      { title: 'Eczema in Babies', searchQuery: 'baby eczema treatment causes how to treat', description: 'Managing eczema in infants', tags: ['Baby'] },
      { title: 'Eczema vs Psoriasis', searchQuery: 'eczema vs psoriasis difference symptoms', description: 'How to tell eczema from psoriasis', tags: ['Comparison'] },
      { title: 'Eczema Diet', searchQuery: 'eczema diet foods to eat and avoid', description: 'Dietary changes for eczema', tags: ['Diet'] },
      { title: 'Topical Treatments', searchQuery: 'topical treatments eczema steroid cream alternatives', description: 'Topical options for eczema', tags: ['Topical'] },
      { title: 'Eczema and Stress', searchQuery: 'stress eczema connection management tips', description: 'How stress affects eczema', tags: ['Stress'] },
      { title: 'Eczema Natural Remedies', searchQuery: 'natural remedies eczema home treatment', description: 'Natural approaches to eczema', tags: ['Natural'] },
    ],
  },
  {
    id: 'psoriasis',
    name: 'Psoriasis Pictures Lichen Planus And Related Diseases',
    displayName: 'Psoriasis & Lichen Planus',
    category: 'Inflammatory',
    color: 'bg-fuchsia-600',
    youtubeSearch: 'psoriasis lichen planus treatment dermatology',
    videos: [
      { title: 'Psoriasis Complete Guide', searchQuery: 'psoriasis causes symptoms treatment complete guide', description: 'Everything about psoriasis', tags: ['Guide'] },
      { title: 'Psoriasis Treatment 2024', searchQuery: 'psoriasis treatment options 2024 dermatologist', description: 'Latest psoriasis treatments', tags: ['Treatment'] },
      { title: 'Lichen Planus Overview', searchQuery: 'lichen planus symptoms treatment dermatology', description: 'Understanding lichen planus', tags: ['Lichen Planus'] },
      { title: 'Biologics for Psoriasis', searchQuery: 'biologics psoriasis treatment explained', description: 'Biologic therapies for psoriasis', tags: ['Biologics'] },
      { title: 'Scalp Psoriasis', searchQuery: 'scalp psoriasis treatment shampoo dermatologist', description: 'Treating scalp psoriasis', tags: ['Scalp'] },
      { title: 'Psoriasis Diet', searchQuery: 'psoriasis diet lifestyle changes treatment', description: 'Diet and lifestyle for psoriasis', tags: ['Diet'] },
      { title: 'Psoriatic Arthritis', searchQuery: 'psoriatic arthritis symptoms treatment', description: 'Psoriasis and joint involvement', tags: ['Arthritis'] },
      { title: 'Phototherapy for Psoriasis', searchQuery: 'phototherapy light therapy psoriasis treatment', description: 'Light therapy for psoriasis', tags: ['Phototherapy'] },
      { title: 'Psoriasis Triggers', searchQuery: 'psoriasis triggers flares how to avoid', description: 'What triggers psoriasis flares', tags: ['Triggers'] },
      { title: 'Psoriasis Skincare', searchQuery: 'psoriasis skincare routine moisturizer', description: 'Daily care for psoriasis', tags: ['Skincare'] },
    ],
  },
  {
    id: 'melanoma',
    name: 'Melanoma Skin Cancer Nevi And Moles',
    displayName: 'Melanoma & Moles',
    category: 'Malignant',
    color: 'bg-gray-800',
    youtubeSearch: 'melanoma skin cancer moles detection treatment',
    videos: [
      { title: 'Melanoma Early Detection', searchQuery: 'melanoma early detection signs dermatologist', description: 'Catching melanoma early', tags: ['Detection'] },
      { title: 'ABCDE Rule', searchQuery: 'ABCDE rule melanoma moles how to check', description: 'The ABCDE method for moles', tags: ['ABCDE'] },
      { title: 'Atypical Moles Guide', searchQuery: 'atypical moles dysplastic nevi melanoma risk', description: 'Understanding atypical moles', tags: ['Moles'] },
      { title: 'Melanoma Treatment', searchQuery: 'melanoma treatment options immunotherapy surgery', description: 'Treatment approaches for melanoma', tags: ['Treatment'] },
      { title: 'Dermoscopy Explained', searchQuery: 'dermoscopy mole evaluation skin cancer', description: 'Dermoscopy for mole assessment', tags: ['Dermoscopy'] },
      { title: 'Skin Self-Exam', searchQuery: 'skin self examination guide how to check moles', description: 'How to examine your skin monthly', tags: ['Self-exam'] },
      { title: 'UV and Melanoma Risk', searchQuery: 'UV radiation melanoma risk prevention sunscreen', description: 'UV exposure and melanoma', tags: ['UV risk'] },
      { title: 'Immunotherapy for Melanoma', searchQuery: 'immunotherapy melanoma treatment success rate', description: 'Immunotherapy breakthroughs', tags: ['Immunotherapy'] },
      { title: 'Melanoma Surgery', searchQuery: 'melanoma surgery wide excision procedure', description: 'Surgical treatment for melanoma', tags: ['Surgery'] },
      { title: 'Melanoma Staging', searchQuery: 'melanoma staging prognosis survival rate', description: 'Stages of melanoma explained', tags: ['Staging'] },
    ],
  },
  {
    id: 'hair_loss',
    name: 'Hair Loss Photos Alopecia And Other Hair Diseases',
    displayName: 'Hair Loss & Alopecia',
    category: 'Hair Disorders',
    color: 'bg-purple-600',
    youtubeSearch: 'hair loss alopecia treatment dermatology',
    videos: [
      { title: 'Alopecia Areata Treatment', searchQuery: 'alopecia areata treatment causes dermatologist', description: 'Understanding and treating alopecia areata', tags: ['Alopecia'] },
      { title: 'Types of Hair Loss', searchQuery: 'types of hair loss explained dermatology', description: 'Different types of alopecia', tags: ['Types'] },
      { title: 'Minoxidil Guide', searchQuery: 'minoxidil hair loss treatment how to use', description: 'Using minoxidil effectively', tags: ['Minoxidil'] },
      { title: 'Female Pattern Hair Loss', searchQuery: 'female pattern hair loss treatment causes', description: 'Hair loss in women', tags: ['Female'] },
      { title: 'Male Pattern Baldness', searchQuery: 'male pattern baldness DHT treatment options', description: 'Understanding male baldness', tags: ['Male'] },
      { title: 'PRP for Hair Loss', searchQuery: 'PRP platelet rich plasma hair loss treatment', description: 'PRP therapy for hair loss', tags: ['PRP'] },
      { title: 'Telogen Effluvium', searchQuery: 'telogen effluvium stress hair loss treatment', description: 'Stress-related hair shedding', tags: ['Telogen'] },
      { title: 'Hair Transplant', searchQuery: 'hair transplant procedure what to expect', description: 'Hair transplant overview', tags: ['Transplant'] },
      { title: 'Scalp Health', searchQuery: 'scalp health hair growth tips dermatologist', description: 'Healthy scalp for hair growth', tags: ['Scalp'] },
      { title: 'Finasteride Guide', searchQuery: 'finasteride hair loss treatment side effects', description: 'Finasteride for hair loss', tags: ['Finasteride'] },
    ],
  },
  {
    id: 'urticaria',
    name: 'Urticaria Hives',
    displayName: 'Urticaria (Hives)',
    category: 'Inflammatory',
    color: 'bg-rose-400',
    youtubeSearch: 'urticaria hives treatment causes dermatology',
    videos: [
      { title: 'Urticaria Overview', searchQuery: 'urticaria hives causes symptoms treatment', description: 'Complete guide to hives', tags: ['Overview'] },
      { title: 'Chronic Hives Guide', searchQuery: 'chronic urticaria hives treatment management', description: 'Managing chronic hives', tags: ['Chronic'] },
      { title: 'Antihistamines for Hives', searchQuery: 'antihistamines hives urticaria treatment guide', description: 'Using antihistamines for hives', tags: ['Antihistamines'] },
      { title: 'Hives Triggers', searchQuery: 'hives triggers identification how to avoid', description: 'Finding your hive triggers', tags: ['Triggers'] },
      { title: 'Stress and Hives', searchQuery: 'stress hives urticaria connection management', description: 'Stress-induced hives', tags: ['Stress'] },
      { title: 'Food Allergy Hives', searchQuery: 'food allergy hives urticaria treatment', description: 'Food-triggered hives', tags: ['Food allergy'] },
      { title: 'Angioedema', searchQuery: 'angioedema vs urticaria treatment emergency', description: 'Angioedema and hives', tags: ['Angioedema'] },
      { title: 'Xolair for Hives', searchQuery: 'omalizumab xolair chronic urticaria treatment', description: 'Biologic for chronic hives', tags: ['Xolair'] },
      { title: 'Emergency Hives Treatment', searchQuery: 'severe hives emergency treatment anaphylaxis', description: 'When hives are an emergency', tags: ['Emergency'] },
      { title: 'Physical Urticaria', searchQuery: 'physical urticaria types cold heat pressure', description: 'Types of physical urticaria', tags: ['Physical'] },
    ],
  },
  {
    id: 'rashes',
    name: 'Rashes',
    displayName: 'Skin Rashes',
    category: 'Inflammatory',
    color: 'bg-red-400',
    youtubeSearch: 'skin rash identification treatment dermatology',
    videos: [
      { title: 'Common Skin Rashes', searchQuery: 'common skin rashes identification treatment', description: 'Guide to common rashes', tags: ['Common'] },
      { title: 'How to Identify Rashes', searchQuery: 'how to identify skin rash diagnosis', description: 'Diagnosing different rashes', tags: ['Identification'] },
      { title: 'Heat Rash Treatment', searchQuery: 'heat rash prickly heat treatment prevention', description: 'Heat rash guide', tags: ['Heat'] },
      { title: 'Viral Rashes', searchQuery: 'viral skin rash children adults treatment', description: 'Rashes from viral infections', tags: ['Viral'] },
      { title: 'Stress Rash', searchQuery: 'stress rash causes treatment anxiety skin', description: 'Stress-induced rashes', tags: ['Stress'] },
      { title: 'Drug Rashes', searchQuery: 'drug rash allergic reaction skin treatment', description: 'Medication-induced rashes', tags: ['Drug'] },
      { title: 'Dangerous Rashes', searchQuery: 'dangerous rashes symptoms when to see doctor', description: 'When rashes need urgent care', tags: ['Dangerous'] },
      { title: 'Antihistamines for Rashes', searchQuery: 'antihistamines rash treatment itching relief', description: 'Using antihistamines for rashes', tags: ['Treatment'] },
      { title: 'Cortisone Cream Guide', searchQuery: 'cortisone cream rash treatment how to use', description: 'Using steroid cream for rashes', tags: ['Cortisone'] },
      { title: 'Rash in Children', searchQuery: 'rash in children common causes treatment pediatric', description: 'Rashes in kids', tags: ['Children'] },
    ],
  },
  {
    id: 'contact_dermatitis',
    name: 'Poison Ivy Photos And Other Contact Dermatitis',
    displayName: 'Contact Dermatitis',
    category: 'Inflammatory',
    color: 'bg-green-700',
    youtubeSearch: 'contact dermatitis poison ivy treatment dermatology',
    videos: [
      { title: 'Contact Dermatitis Guide', searchQuery: 'contact dermatitis causes symptoms treatment', description: 'Complete contact dermatitis overview', tags: ['Overview'] },
      { title: 'Poison Ivy Rash', searchQuery: 'poison ivy rash treatment how to treat', description: 'Dealing with poison ivy', tags: ['Poison ivy'] },
      { title: 'Allergic vs Irritant CD', searchQuery: 'allergic vs irritant contact dermatitis difference', description: 'Types of contact dermatitis', tags: ['Types'] },
      { title: 'Patch Testing', searchQuery: 'patch testing contact allergy dermatology', description: 'Testing for contact allergies', tags: ['Patch test'] },
      { title: 'Nickel Allergy', searchQuery: 'nickel allergy contact dermatitis jewelry skin', description: 'Nickel contact allergy', tags: ['Nickel'] },
      { title: 'Occupational CD', searchQuery: 'occupational contact dermatitis work skin', description: 'Work-related contact dermatitis', tags: ['Occupational'] },
      { title: 'Cosmetic Allergy', searchQuery: 'cosmetic contact dermatitis allergic reaction skin', description: 'Skincare product allergies', tags: ['Cosmetic'] },
      { title: 'Prevention of CD', searchQuery: 'how to prevent contact dermatitis skin protection', description: 'Preventing contact dermatitis', tags: ['Prevention'] },
      { title: 'Treating CD', searchQuery: 'how to treat contact dermatitis fast relief', description: 'Fast relief from contact dermatitis', tags: ['Treatment'] },
      { title: 'Fragrance Allergy', searchQuery: 'fragrance allergy skin care products reaction', description: 'Fragrance-induced skin reactions', tags: ['Fragrance'] },
    ],
  },
  {
    id: 'athletes_foot',
    name: 'Fu Athlete Foot',
    displayName: "Athlete's Foot",
    category: 'Fungal',
    color: 'bg-teal-500',
    youtubeSearch: "athlete's foot fungal infection treatment",
    videos: [
      { title: "Athlete's Foot Guide", searchQuery: "athlete's foot tinea pedis treatment causes", description: "Complete guide to athlete's foot", tags: ['Overview'] },
      { title: 'Best Antifungal Creams', searchQuery: "best antifungal cream athlete's foot treatment", description: 'Top antifungal products', tags: ['Antifungal'] },
      { title: "Preventing Athlete's Foot", searchQuery: "how to prevent athlete's foot hygiene tips", description: "Prevention strategies", tags: ['Prevention'] },
      { title: 'Home Remedies', searchQuery: "athlete's foot home remedies treatment", description: 'Natural treatment options', tags: ['Home remedies'] },
      { title: 'Oral Antifungals', searchQuery: 'oral antifungal medication foot infection treatment', description: 'Oral medication options', tags: ['Oral treatment'] },
      { title: 'Hygiene Tips', searchQuery: "athlete's foot hygiene prevention foot care", description: 'Foot hygiene guide', tags: ['Hygiene'] },
      { title: 'Foot Infection Types', searchQuery: 'fungal foot infection types treatment comparison', description: 'Types of foot infections', tags: ['Types'] },
      { title: 'Chronic Athlete\'s Foot', searchQuery: "chronic athlete's foot treatment recurrence", description: 'Managing recurring infections', tags: ['Chronic'] },
      { title: "Athlete's Foot vs Eczema", searchQuery: "athlete's foot vs eczema feet difference", description: 'Telling the two conditions apart', tags: ['Comparison'] },
      { title: 'When Infection Spreads', searchQuery: "athlete's foot spread to nails body treatment", description: 'Managing spreading infection', tags: ['Spreading'] },
    ],
  },
  {
    id: 'nail_fungus',
    name: 'Fu Nail Fungus',
    displayName: 'Nail Fungus',
    category: 'Fungal',
    color: 'bg-teal-600',
    youtubeSearch: 'nail fungus onychomycosis treatment dermatology',
    videos: [
      { title: 'Nail Fungus Treatment', searchQuery: 'nail fungus treatment that works dermatologist', description: 'Effective nail fungus treatments', tags: ['Treatment'] },
      { title: 'Onychomycosis Guide', searchQuery: 'onychomycosis nail fungus causes treatment', description: 'Medical overview of nail fungus', tags: ['Medical'] },
      { title: 'Terbinafine for Nails', searchQuery: 'terbinafine nail fungus treatment duration', description: 'Oral terbinafine guide', tags: ['Terbinafine'] },
      { title: 'Laser Nail Treatment', searchQuery: 'laser treatment nail fungus does it work', description: 'Laser therapy for nails', tags: ['Laser'] },
      { title: 'Preventing Nail Fungus', searchQuery: 'how to prevent nail fungus tips hygiene', description: 'Prevention strategies', tags: ['Prevention'] },
      { title: 'Nail Fungus vs Psoriasis', searchQuery: 'nail fungus vs nail psoriasis difference', description: 'Distinguishing nail conditions', tags: ['Comparison'] },
      { title: 'Home Remedies', searchQuery: 'nail fungus home remedies tea tree oil', description: 'Home treatments for nail fungus', tags: ['Home remedies'] },
      { title: 'Topical Nail Treatment', searchQuery: 'topical antifungal nail treatment efinaconazole', description: 'Topical options for nail fungus', tags: ['Topical'] },
      { title: 'How Long to Treat', searchQuery: 'nail fungus treatment duration how long results', description: 'Timeline for nail fungus treatment', tags: ['Timeline'] },
      { title: 'Nail Fungus Risk Factors', searchQuery: 'nail fungus risk factors diabetes elderly', description: 'Who is at risk for nail fungus', tags: ['Risk factors'] },
    ],
  },
  {
    id: 'ringworm',
    name: 'Fu Ringworm',
    displayName: 'Ringworm',
    category: 'Fungal',
    color: 'bg-teal-400',
    youtubeSearch: 'ringworm tinea treatment dermatology',
    videos: [
      { title: 'Ringworm Treatment', searchQuery: 'ringworm tinea treatment antifungal cream', description: 'Treating ringworm effectively', tags: ['Treatment'] },
      { title: 'Ringworm vs Eczema', searchQuery: 'ringworm vs eczema how to tell difference', description: 'Telling them apart', tags: ['Comparison'] },
      { title: 'Ringworm in Children', searchQuery: 'ringworm children school treatment parent guide', description: 'Managing ringworm in kids', tags: ['Children'] },
      { title: 'Scalp Ringworm', searchQuery: 'scalp ringworm tinea capitis treatment', description: 'Ringworm of the scalp', tags: ['Scalp'] },
      { title: 'Preventing Ringworm Spread', searchQuery: 'how to prevent ringworm from spreading contagious', description: 'Stopping ringworm transmission', tags: ['Prevention'] },
      { title: 'Ringworm from Pets', searchQuery: 'ringworm from pets cats dogs zoonotic treatment', description: 'Pet-to-human ringworm', tags: ['Pets'] },
      { title: 'Best Antifungals', searchQuery: 'best antifungal cream ringworm clotrimazole', description: 'Top antifungal options', tags: ['Antifungal'] },
      { title: 'Oral Treatment for Ringworm', searchQuery: 'oral antifungal ringworm griseofulvin terbinafine', description: 'When to use oral treatment', tags: ['Oral'] },
      { title: 'Ringworm Duration', searchQuery: 'how long does ringworm last treatment timeline', description: 'Healing timeline', tags: ['Timeline'] },
      { title: 'Ringworm Misdiagnosis', searchQuery: 'ringworm misdiagnosed conditions similar look', description: 'Conditions that look like ringworm', tags: ['Diagnosis'] },
    ],
  },
  {
    id: 'cellulitis',
    name: 'Ba  Cellulitis',
    displayName: 'Cellulitis',
    category: 'Bacterial',
    color: 'bg-yellow-600',
    youtubeSearch: 'cellulitis bacterial skin infection treatment',
    videos: [
      { title: 'Cellulitis Overview', searchQuery: 'cellulitis skin infection causes treatment', description: 'Understanding cellulitis', tags: ['Overview'] },
      { title: 'Cellulitis vs Erysipelas', searchQuery: 'cellulitis vs erysipelas difference treatment', description: 'Distinguishing bacterial skin infections', tags: ['Comparison'] },
      { title: 'When to Go to Hospital', searchQuery: 'cellulitis when to go hospital emergency signs', description: 'Emergency warning signs', tags: ['Emergency'] },
      { title: 'Antibiotics for Cellulitis', searchQuery: 'antibiotics cellulitis treatment duration', description: 'Antibiotic treatment guide', tags: ['Antibiotics'] },
      { title: 'Preventing Recurrence', searchQuery: 'recurrent cellulitis prevention treatment', description: 'Stopping cellulitis from coming back', tags: ['Prevention'] },
      { title: 'Cellulitis in Diabetics', searchQuery: 'cellulitis diabetic patients treatment complications', description: 'Cellulitis in high-risk patients', tags: ['Diabetes'] },
      { title: 'Wound Care', searchQuery: 'cellulitis wound care management treatment', description: 'Wound care for cellulitis', tags: ['Wound care'] },
      { title: 'Signs of Infection', searchQuery: 'serious skin infection signs symptoms treatment', description: 'Recognizing serious infections', tags: ['Signs'] },
      { title: 'Cellulitis Recovery', searchQuery: 'cellulitis recovery time aftercare treatment', description: 'Recovery timeline and care', tags: ['Recovery'] },
      { title: 'MRSA vs Cellulitis', searchQuery: 'MRSA vs cellulitis difference treatment', description: 'MRSA and cellulitis comparison', tags: ['MRSA'] },
    ],
  },
  {
    id: 'impetigo',
    name: 'Ba Impetigo',
    displayName: 'Impetigo',
    category: 'Bacterial',
    color: 'bg-yellow-500',
    youtubeSearch: 'impetigo bacterial skin infection treatment',
    videos: [
      { title: 'Impetigo Guide', searchQuery: 'impetigo what is it treatment causes', description: 'Complete impetigo overview', tags: ['Overview'] },
      { title: 'Impetigo in Children', searchQuery: 'impetigo in children treatment school contagious', description: 'Managing impetigo in kids', tags: ['Children'] },
      { title: 'Antibiotic Treatment', searchQuery: 'antibiotic treatment impetigo mupirocin fusidic acid', description: 'Antibiotic options for impetigo', tags: ['Antibiotics'] },
      { title: 'Preventing Spread', searchQuery: 'impetigo how to prevent spreading contagious', description: 'Stopping impetigo transmission', tags: ['Prevention'] },
      { title: 'Bullous Impetigo', searchQuery: 'bullous impetigo treatment causes blisters', description: 'Blistering form of impetigo', tags: ['Bullous'] },
      { title: 'Impetigo vs Cold Sores', searchQuery: 'impetigo vs cold sores herpes difference', description: 'Telling them apart', tags: ['Comparison'] },
      { title: 'Home Care Guide', searchQuery: 'impetigo home care wound cleaning treatment', description: 'Caring for impetigo at home', tags: ['Home care'] },
      { title: 'Impetigo Complications', searchQuery: 'impetigo complications post-streptococcal', description: 'Potential complications', tags: ['Complications'] },
      { title: 'Back to School', searchQuery: 'impetigo school return policy contagious period', description: 'When kids can return to school', tags: ['School'] },
      { title: 'Recurrent Impetigo', searchQuery: 'recurrent impetigo causes prevention decolonization', description: 'Stopping recurrences', tags: ['Recurrent'] },
    ],
  },
  {
    id: 'bacterial_infections',
    name: 'Cellulitis Impetigo And Other Bacterial Infections',
    displayName: 'Bacterial Skin Infections',
    category: 'Bacterial',
    color: 'bg-amber-600',
    youtubeSearch: 'bacterial skin infection treatment types',
    videos: [
      { title: 'Bacterial Skin Infections Overview', searchQuery: 'bacterial skin infections overview types treatment', description: 'Types of bacterial skin infections', tags: ['Overview'] },
      { title: 'MRSA Skin Infection', searchQuery: 'MRSA skin infection symptoms treatment', description: 'MRSA overview', tags: ['MRSA'] },
      { title: 'Folliculitis Treatment', searchQuery: 'folliculitis causes treatment prevention', description: 'Hair follicle infections', tags: ['Folliculitis'] },
      { title: 'Furuncles and Carbuncles', searchQuery: 'furuncle carbuncle boil treatment drainage', description: 'Boils and carbuncles', tags: ['Boils'] },
      { title: 'Staph Skin Infections', searchQuery: 'staphylococcal skin infection treatment types', description: 'Staph infections overview', tags: ['Staph'] },
      { title: 'Strep Skin Infections', searchQuery: 'streptococcal skin infection treatment signs', description: 'Strep skin infections', tags: ['Strep'] },
      { title: 'Prevention Guide', searchQuery: 'bacterial skin infection prevention hygiene', description: 'Preventing skin infections', tags: ['Prevention'] },
      { title: 'Antibiotic Resistance', searchQuery: 'antibiotic resistance skin infections MRSA', description: 'Antibiotic resistance in skin', tags: ['Resistance'] },
      { title: 'When to See a Doctor', searchQuery: 'skin infection when to see doctor warning signs', description: 'Warning signs for skin infections', tags: ['Warning signs'] },
      { title: 'Wound Infection', searchQuery: 'wound infection signs treatment prevention', description: 'Infected wound management', tags: ['Wound'] },
    ],
  },
  {
    id: 'bullous_disease',
    name: 'Bullous Disease Photos',
    displayName: 'Bullous Disease',
    category: 'Autoimmune',
    color: 'bg-indigo-500',
    youtubeSearch: 'bullous disease pemphigoid blistering skin treatment',
    videos: [
      { title: 'Bullous Pemphigoid', searchQuery: 'bullous pemphigoid causes treatment management', description: 'Overview of bullous pemphigoid', tags: ['Pemphigoid'] },
      { title: 'Pemphigus Vulgaris', searchQuery: 'pemphigus vulgaris treatment autoimmune blistering', description: 'Understanding pemphigus', tags: ['Pemphigus'] },
      { title: 'Autoimmune Blistering', searchQuery: 'autoimmune blistering skin diseases overview', description: 'Autoimmune blister conditions', tags: ['Autoimmune'] },
      { title: 'Blisters on Skin', searchQuery: 'blisters on skin causes treatment dermatology', description: 'Managing skin blisters', tags: ['Blisters'] },
      { title: 'Dermatitis Herpetiformis', searchQuery: 'dermatitis herpetiformis celiac skin treatment', description: 'DH and celiac disease', tags: ['DH'] },
      { title: 'Treatment Options', searchQuery: 'bullous pemphigoid treatment corticosteroids', description: 'Treatment for bullous disease', tags: ['Treatment'] },
      { title: 'Epidermolysis Bullosa', searchQuery: 'epidermolysis bullosa symptoms treatment management', description: 'EB overview', tags: ['EB'] },
      { title: 'Wound Care', searchQuery: 'blistering skin disease wound care management', description: 'Caring for blisters and wounds', tags: ['Wound care'] },
      { title: 'Drug-Induced Blisters', searchQuery: 'drug induced blistering skin reaction treatment', description: 'Medication-induced blistering', tags: ['Drug-induced'] },
      { title: 'Living with Bullous Disease', searchQuery: 'living with bullous disease quality of life', description: 'Managing daily life with BD', tags: ['Quality of life'] },
    ],
  },
  {
    id: 'drug_eruptions',
    name: 'Exanthems And Drug Eruptions',
    displayName: 'Exanthems & Drug Eruptions',
    category: 'Reactive',
    color: 'bg-rose-500',
    youtubeSearch: 'drug eruption exanthem skin reaction treatment',
    videos: [
      { title: 'Drug Rashes Overview', searchQuery: 'drug rash eruption types treatment management', description: 'Types of drug reactions', tags: ['Overview'] },
      { title: 'Stevens-Johnson Syndrome', searchQuery: 'Stevens Johnson syndrome SJS treatment emergency', description: 'Severe drug reaction', tags: ['SJS'] },
      { title: 'Morbilliform Drug Eruption', searchQuery: 'morbilliform drug eruption treatment diagnosis', description: 'Common drug rash pattern', tags: ['Morbilliform'] },
      { title: 'Drug Allergy vs Reaction', searchQuery: 'drug allergy vs drug reaction difference treatment', description: 'Allergy versus intolerance', tags: ['Allergy'] },
      { title: 'DRESS Syndrome', searchQuery: 'DRESS syndrome drug reaction eosinophilia treatment', description: 'Severe drug hypersensitivity', tags: ['DRESS'] },
      { title: 'Fixed Drug Eruption', searchQuery: 'fixed drug eruption treatment diagnosis', description: 'Fixed location drug rash', tags: ['Fixed'] },
      { title: 'Viral Exanthems', searchQuery: 'viral exanthem children adults treatment rash', description: 'Viral skin eruptions', tags: ['Viral'] },
      { title: 'Photosensitivity Reaction', searchQuery: 'drug photosensitivity reaction treatment prevention', description: 'Sun-triggered drug reactions', tags: ['Photosensitivity'] },
      { title: 'Managing Drug Eruptions', searchQuery: 'managing drug eruptions home treatment antihistamine', description: 'Home management of drug rashes', tags: ['Management'] },
      { title: 'Drug Eruption Testing', searchQuery: 'drug reaction testing patch test graded challenge', description: 'Testing for drug sensitivity', tags: ['Testing'] },
    ],
  },
  {
    id: 'herpes_hpv',
    name: 'Herpes Hpv And Other Stds Photos',
    displayName: 'Herpes, HPV & STDs',
    category: 'Viral',
    color: 'bg-pink-600',
    youtubeSearch: 'herpes HPV sexually transmitted infections skin treatment',
    videos: [
      { title: 'Herpes Simplex Explained', searchQuery: 'herpes simplex virus HSV treatment management', description: 'HSV overview', tags: ['Herpes'] },
      { title: 'HPV What to Know', searchQuery: 'HPV human papillomavirus symptoms treatment', description: 'HPV complete guide', tags: ['HPV'] },
      { title: 'Genital Herpes Treatment', searchQuery: 'genital herpes treatment antivirals management', description: 'Managing genital herpes', tags: ['Genital'] },
      { title: 'HPV Vaccine', searchQuery: 'HPV vaccine importance who should get it', description: 'HPV vaccination guide', tags: ['Vaccine'] },
      { title: 'Living with Herpes', searchQuery: 'living with herpes management tips disclosure', description: 'Coping with herpes', tags: ['Living with'] },
      { title: 'STD Prevention', searchQuery: 'STD prevention what works sexual health', description: 'Preventing STDs', tags: ['Prevention'] },
      { title: 'Herpes Outbreak Triggers', searchQuery: 'herpes outbreak triggers prevention management', description: 'What triggers outbreaks', tags: ['Triggers'] },
      { title: 'Antiviral Medications', searchQuery: 'antiviral medications herpes acyclovir valacyclovir', description: 'Antivirals for herpes', tags: ['Antivirals'] },
      { title: 'HPV and Warts', searchQuery: 'HPV genital warts treatment removal', description: 'HPV-related warts', tags: ['Warts'] },
      { title: 'STD Testing Guide', searchQuery: 'STD testing when how types sexual health', description: 'STD testing guide', tags: ['Testing'] },
    ],
  },
  {
    id: 'pigmentation',
    name: 'Light Diseases And Disorders Of Pigmentation',
    displayName: 'Pigmentation Disorders',
    category: 'Pigmentation',
    color: 'bg-amber-400',
    youtubeSearch: 'skin pigmentation disorders vitiligo melasma treatment',
    videos: [
      { title: 'Vitiligo Treatment', searchQuery: 'vitiligo treatment causes repigmentation', description: 'Managing vitiligo', tags: ['Vitiligo'] },
      { title: 'Melasma Treatment', searchQuery: 'melasma treatment hyperpigmentation dermatologist', description: 'Treating melasma effectively', tags: ['Melasma'] },
      { title: 'Hyperpigmentation Guide', searchQuery: 'hyperpigmentation treatment prevention causes', description: 'Understanding dark spots', tags: ['Hyperpigmentation'] },
      { title: 'PIH Treatment', searchQuery: 'post inflammatory hyperpigmentation treatment dark spots', description: 'Post-inflammatory dark spots', tags: ['PIH'] },
      { title: 'Niacinamide for Dark Spots', searchQuery: 'niacinamide dark spots hyperpigmentation treatment', description: 'Niacinamide for pigmentation', tags: ['Niacinamide'] },
      { title: 'Sunscreen for Pigmentation', searchQuery: 'sunscreen pigmentation control hyperpigmentation prevention', description: 'Sun protection role', tags: ['Sunscreen'] },
      { title: 'Chemical Peels', searchQuery: 'chemical peel hyperpigmentation dark spots treatment', description: 'Peels for pigmentation', tags: ['Peels'] },
      { title: 'Retinoids for Dark Spots', searchQuery: 'retinoid retinol dark spots hyperpigmentation', description: 'Retinoids for pigmentation', tags: ['Retinoids'] },
      { title: 'Vitiligo Repigmentation', searchQuery: 'vitiligo repigmentation treatment NB-UVB therapy', description: 'Repigmentation options', tags: ['Repigmentation'] },
      { title: 'Albinism Overview', searchQuery: 'albinism causes management skin care protection', description: 'Understanding albinism', tags: ['Albinism'] },
    ],
  },
  {
    id: 'lupus',
    name: 'Lupus And Other Connective Tissue Diseases',
    displayName: 'Lupus & Connective Tissue',
    category: 'Autoimmune',
    color: 'bg-violet-600',
    youtubeSearch: 'lupus skin connective tissue disease treatment',
    videos: [
      { title: 'Lupus Overview', searchQuery: 'lupus erythematosus symptoms causes treatment', description: 'Understanding lupus', tags: ['Overview'] },
      { title: 'Cutaneous Lupus', searchQuery: 'cutaneous lupus erythematosus skin treatment', description: 'Skin involvement in lupus', tags: ['Cutaneous'] },
      { title: 'Butterfly Rash', searchQuery: 'lupus butterfly rash malar rash causes', description: 'Lupus butterfly rash explained', tags: ['Butterfly rash'] },
      { title: 'Scleroderma', searchQuery: 'scleroderma systemic sclerosis treatment overview', description: 'Understanding scleroderma', tags: ['Scleroderma'] },
      { title: 'Living with Lupus', searchQuery: 'living with lupus management lifestyle tips', description: 'Managing lupus daily', tags: ['Living with'] },
      { title: 'Lupus Treatment Options', searchQuery: 'lupus treatment hydroxychloroquine biologics', description: 'Treatment approaches', tags: ['Treatment'] },
      { title: 'Lupus Flares', searchQuery: 'lupus flares triggers prevention management', description: 'Managing flares', tags: ['Flares'] },
      { title: 'Lupus and Sun', searchQuery: 'lupus sun sensitivity photosensitivity protection', description: 'Sun sensitivity in lupus', tags: ['Sun sensitivity'] },
      { title: 'Dermatomyositis', searchQuery: 'dermatomyositis skin muscle disease treatment', description: 'Skin and muscle involvement', tags: ['DM'] },
      { title: 'Lupus Diagnosis', searchQuery: 'lupus diagnosis blood tests ANA criteria', description: 'How lupus is diagnosed', tags: ['Diagnosis'] },
    ],
  },
  {
    id: 'malignant',
    name: 'Malignant',
    displayName: 'Malignant Skin Conditions',
    category: 'Malignant',
    color: 'bg-slate-700',
    youtubeSearch: 'malignant skin cancer treatment dermatology',
    videos: [
      { title: 'Malignant Skin Tumors', searchQuery: 'malignant skin tumors types treatment overview', description: 'Overview of skin cancers', tags: ['Overview'] },
      { title: 'Squamous Cell Carcinoma', searchQuery: 'squamous cell carcinoma skin cancer treatment', description: 'SCC overview', tags: ['SCC'] },
      { title: 'Immunotherapy for Skin Cancer', searchQuery: 'immunotherapy skin cancer treatment checkpoint inhibitor', description: 'Immunotherapy breakthroughs', tags: ['Immunotherapy'] },
      { title: 'Radiation for Skin Cancer', searchQuery: 'radiation therapy skin cancer treatment', description: 'Radiation therapy guide', tags: ['Radiation'] },
      { title: 'Targeted Therapy', searchQuery: 'targeted therapy melanoma BRAF inhibitor', description: 'Targeted cancer treatment', tags: ['Targeted'] },
      { title: 'Skin Cancer Staging', searchQuery: 'skin cancer staging TNM system treatment', description: 'How skin cancer is staged', tags: ['Staging'] },
      { title: 'Merkel Cell Carcinoma', searchQuery: 'Merkel cell carcinoma rare skin cancer treatment', description: 'Rare skin cancer type', tags: ['Merkel'] },
      { title: 'Cutaneous Lymphoma', searchQuery: 'cutaneous T cell lymphoma CTCL treatment', description: 'Skin lymphoma', tags: ['Lymphoma'] },
      { title: 'Kaposi Sarcoma', searchQuery: 'Kaposi sarcoma treatment HIV skin lesions', description: 'Kaposi sarcoma overview', tags: ['KS'] },
      { title: 'Mohs Surgery', searchQuery: 'Mohs surgery skin cancer procedure results', description: 'Mohs surgical technique', tags: ['Mohs'] },
    ],
  },
  {
    id: 'nail_disease',
    name: 'Nail Fungus And Other Nail Disease',
    displayName: 'Nail Diseases',
    category: 'Nail Disorders',
    color: 'bg-cyan-600',
    youtubeSearch: 'nail disease disorders treatment dermatology',
    videos: [
      { title: 'Nail Diseases Overview', searchQuery: 'nail diseases overview types treatment dermatology', description: 'Common nail conditions', tags: ['Overview'] },
      { title: 'Nail Psoriasis', searchQuery: 'nail psoriasis pitting treatment dermatology', description: 'Psoriasis affecting nails', tags: ['Psoriasis'] },
      { title: 'Ingrown Toenail', searchQuery: 'ingrown toenail treatment prevention surgery', description: 'Treating ingrown nails', tags: ['Ingrown'] },
      { title: 'Paronychia', searchQuery: 'paronychia nail fold infection treatment', description: 'Nail fold infection', tags: ['Paronychia'] },
      { title: 'Black Toenail', searchQuery: 'black toenail subungual hematoma treatment runner', description: 'Treating black toenails', tags: ['Black nail'] },
      { title: 'Brittle Nails', searchQuery: 'brittle nails causes treatment biotin strengthening', description: 'Managing brittle nails', tags: ['Brittle'] },
      { title: 'Nail Pitting', searchQuery: 'nail pitting causes systemic disease dermatology', description: 'Nail pitting explained', tags: ['Pitting'] },
      { title: 'Onycholysis', searchQuery: 'onycholysis nail separation causes treatment', description: 'Nail plate separation', tags: ['Onycholysis'] },
      { title: 'Healthy Nail Care', searchQuery: 'healthy nail care tips dermatologist advice', description: 'Nail care guide', tags: ['Care'] },
      { title: 'Beau\'s Lines', searchQuery: "Beau's lines nails causes systemic illness", description: 'Transverse nail grooves', tags: ["Beau's lines"] },
    ],
  },
  {
    id: 'larva_migrans',
    name: 'Pa Cutaneous Larva Migrans',
    displayName: 'Cutaneous Larva Migrans',
    category: 'Parasitic',
    color: 'bg-lime-600',
    youtubeSearch: 'cutaneous larva migrans hookworm skin treatment',
    videos: [
      { title: 'Larva Migrans Explained', searchQuery: 'cutaneous larva migrans hookworm skin infection', description: 'Understanding CLM', tags: ['Overview'] },
      { title: 'Hookworm Skin Infection', searchQuery: 'hookworm cutaneous larva migrans beach sand', description: 'Hookworm in skin', tags: ['Hookworm'] },
      { title: 'Creeping Eruption Treatment', searchQuery: 'creeping eruption treatment ivermectin albendazole', description: 'Treating creeping eruption', tags: ['Treatment'] },
      { title: 'Beach Safety', searchQuery: 'beach safety larva migrans prevention footwear', description: 'Prevention at the beach', tags: ['Prevention'] },
      { title: 'Tropical Skin Infections', searchQuery: 'tropical skin infections parasites treatment', description: 'Tropical parasite infections', tags: ['Tropical'] },
      { title: 'Ivermectin Treatment', searchQuery: 'ivermectin skin parasites treatment dosage', description: 'Ivermectin for CLM', tags: ['Ivermectin'] },
      { title: 'Diagnosis Guide', searchQuery: 'cutaneous larva migrans diagnosis clinical features', description: 'Diagnosing CLM', tags: ['Diagnosis'] },
      { title: 'Travel Medicine Skin', searchQuery: 'travel medicine skin infections prevention tropical', description: 'Skin infections while traveling', tags: ['Travel'] },
      { title: 'Parasitic Skin Diseases', searchQuery: 'parasitic skin diseases types treatment global', description: 'Global parasitic skin conditions', tags: ['Parasitic'] },
      { title: 'Post-Travel Skin Rash', searchQuery: 'post travel skin rash tropical infection diagnosis', description: 'Rashes after travel', tags: ['Post-travel'] },
    ],
  },
  {
    id: 'scabies_lyme',
    name: 'Scabies Lyme Disease And Other Infestations And Bites',
    displayName: 'Scabies, Lyme & Infestations',
    category: 'Parasitic',
    color: 'bg-lime-700',
    youtubeSearch: 'scabies lyme disease skin infestation treatment',
    videos: [
      { title: 'Scabies Treatment', searchQuery: 'scabies treatment permethrin diagnosis itching', description: 'Treating scabies', tags: ['Scabies'] },
      { title: 'Lyme Disease Skin Signs', searchQuery: 'Lyme disease skin signs bull eye rash treatment', description: 'Lyme disease skin manifestations', tags: ['Lyme'] },
      { title: 'Permethrin for Scabies', searchQuery: 'permethrin scabies treatment how to apply', description: 'Using permethrin correctly', tags: ['Permethrin'] },
      { title: 'Tick Removal Guide', searchQuery: 'tick removal guide safe technique prevention', description: 'How to remove ticks safely', tags: ['Ticks'] },
      { title: 'Head Lice Treatment', searchQuery: 'head lice treatment removal shampoo combing', description: 'Managing head lice', tags: ['Lice'] },
      { title: 'Preventing Tick Bites', searchQuery: 'tick bite prevention repellent clothing tips', description: 'Tick bite prevention', tags: ['Prevention'] },
      { title: 'Norwegian Scabies', searchQuery: 'Norwegian crusted scabies severe treatment', description: 'Severe form of scabies', tags: ['Norwegian'] },
      { title: 'Bed Bugs vs Scabies', searchQuery: 'bed bugs vs scabies difference identification', description: 'Telling them apart', tags: ['Comparison'] },
      { title: "Bull's Eye Rash", searchQuery: "lyme disease bull's eye rash erythema migrans", description: 'Classic Lyme disease rash', tags: ["Bull's eye"] },
      { title: 'Insect Bite Reactions', searchQuery: 'insect bite allergic reaction treatment management', description: 'Allergic reactions to bites', tags: ['Bites'] },
    ],
  },
  {
    id: 'seborrheic_keratoses',
    name: 'Seborrheic Keratoses And Other Benign Tumors',
    displayName: 'Seborrheic Keratoses',
    category: 'Benign',
    color: 'bg-stone-500',
    youtubeSearch: 'seborrheic keratosis benign skin tumor treatment removal',
    videos: [
      { title: 'Seborrheic Keratosis Guide', searchQuery: 'seborrheic keratosis what is it treatment removal', description: 'Understanding seborrheic keratosis', tags: ['Overview'] },
      { title: 'SK vs Melanoma', searchQuery: 'seborrheic keratosis vs melanoma how to tell', description: 'Telling apart SK and melanoma', tags: ['Comparison'] },
      { title: 'Removing SK', searchQuery: 'seborrheic keratosis removal cryotherapy electrocautery', description: 'Removal methods for SK', tags: ['Removal'] },
      { title: 'Why We Get SK', searchQuery: 'seborrheic keratosis causes aging genetics sun', description: 'Causes of seborrheic keratosis', tags: ['Causes'] },
      { title: 'Skin Tags Removal', searchQuery: 'skin tags removal treatment options dermatologist', description: 'Getting rid of skin tags', tags: ['Skin tags'] },
      { title: 'Cherry Angiomas', searchQuery: 'cherry angiomas treatment removal causes', description: 'Cherry angioma guide', tags: ['Cherry angioma'] },
      { title: 'Milia Treatment', searchQuery: 'milia treatment removal prevention face', description: 'Dealing with milia', tags: ['Milia'] },
      { title: 'Dermatosis Papulosa Nigra', searchQuery: 'dermatosis papulosa nigra treatment removal', description: 'DPN overview and treatment', tags: ['DPN'] },
      { title: 'Cryotherapy for Lesions', searchQuery: 'cryotherapy benign skin lesions treatment', description: 'Liquid nitrogen treatment', tags: ['Cryotherapy'] },
      { title: 'Age Spots vs SK', searchQuery: 'age spots vs seborrheic keratosis difference', description: 'Age spots vs SK comparison', tags: ['Age spots'] },
    ],
  },
  {
    id: 'systemic_disease',
    name: 'Systemic Disease',
    displayName: 'Systemic Disease & Skin',
    category: 'Systemic',
    color: 'bg-blue-700',
    youtubeSearch: 'systemic disease skin manifestations dermatology',
    videos: [
      { title: 'Skin Signs of Disease', searchQuery: 'skin signs systemic disease diagnosis dermatology', description: 'What skin reveals about health', tags: ['Overview'] },
      { title: 'Diabetes & Skin', searchQuery: 'diabetes skin conditions complications dermatology', description: 'Skin in diabetic patients', tags: ['Diabetes'] },
      { title: 'Thyroid & Skin', searchQuery: 'thyroid disease skin changes manifestations', description: 'Thyroid effects on skin', tags: ['Thyroid'] },
      { title: 'Liver Disease & Skin', searchQuery: 'liver disease skin signs jaundice spider angioma', description: 'Liver disease skin signs', tags: ['Liver'] },
      { title: 'Kidney Disease & Skin', searchQuery: 'kidney disease skin manifestations pruritus uremia', description: 'Renal disease skin signs', tags: ['Kidney'] },
      { title: 'Acanthosis Nigricans', searchQuery: 'acanthosis nigricans insulin resistance treatment', description: 'Metabolic skin sign', tags: ['AN'] },
      { title: 'Sarcoidosis & Skin', searchQuery: 'sarcoidosis skin manifestations lupus pernio', description: 'Sarcoidosis skin involvement', tags: ['Sarcoidosis'] },
      { title: 'IBD & Skin', searchQuery: 'inflammatory bowel disease skin manifestations pyoderma', description: 'Gut-skin connection', tags: ['IBD'] },
      { title: 'Neurofibromatosis', searchQuery: 'neurofibromatosis skin signs cafe au lait spots', description: 'NF skin manifestations', tags: ['NF'] },
      { title: 'Amyloidosis Skin', searchQuery: 'amyloidosis skin manifestations treatment', description: 'Amyloidosis and skin', tags: ['Amyloidosis'] },
    ],
  },
  {
    id: 'tinea_candidiasis',
    name: 'Tinea Ringworm Candidiasis And Other Fungal Infections',
    displayName: 'Tinea & Candidiasis',
    category: 'Fungal',
    color: 'bg-teal-700',
    youtubeSearch: 'tinea candidiasis fungal skin infection treatment',
    videos: [
      { title: 'Tinea Infections Overview', searchQuery: 'tinea infections types treatment antifungal', description: 'All tinea infections', tags: ['Overview'] },
      { title: 'Candidiasis Treatment', searchQuery: 'candidiasis skin yeast infection treatment', description: 'Managing candidiasis', tags: ['Candidiasis'] },
      { title: 'Oral Thrush', searchQuery: 'oral thrush candidiasis treatment fluconazole', description: 'Oral candidiasis', tags: ['Oral thrush'] },
      { title: 'Tinea Versicolor', searchQuery: 'tinea versicolor treatment selenium sulfide', description: 'Pityriasis versicolor', tags: ['Versicolor'] },
      { title: 'Jock Itch', searchQuery: 'jock itch tinea cruris treatment antifungal', description: 'Groin fungal infection', tags: ['Jock itch'] },
      { title: 'Antifungal Medications', searchQuery: 'antifungal medications overview types dermatology', description: 'Types of antifungals', tags: ['Antifungals'] },
      { title: 'Preventing Fungal Infections', searchQuery: 'preventing fungal skin infections hygiene tips', description: 'Fungal infection prevention', tags: ['Prevention'] },
      { title: 'Yeast Skin Infection', searchQuery: 'yeast skin infection candida intertrigo treatment', description: 'Skin yeast infections', tags: ['Yeast'] },
      { title: 'Fluconazole Guide', searchQuery: 'fluconazole fungal infection dosage treatment', description: 'Using fluconazole', tags: ['Fluconazole'] },
      { title: 'Tinea Pedis vs Eczema', searchQuery: 'tinea pedis vs eczema feet difference treatment', description: 'Foot fungus vs eczema', tags: ['Comparison'] },
    ],
  },
  {
    id: 'vascular_tumors',
    name: 'Vascular Tumors',
    displayName: 'Vascular Tumors',
    category: 'Vascular',
    color: 'bg-red-600',
    youtubeSearch: 'vascular skin tumors hemangioma treatment dermatology',
    videos: [
      { title: 'Hemangiomas Overview', searchQuery: 'hemangioma types treatment infantile strawberry', description: 'Types of hemangiomas', tags: ['Hemangioma'] },
      { title: 'Infantile Hemangioma', searchQuery: 'infantile hemangioma baby treatment propranolol', description: 'Hemangiomas in babies', tags: ['Infantile'] },
      { title: 'Port Wine Stains', searchQuery: 'port wine stain treatment laser management', description: 'Port wine birthmarks', tags: ['Port wine'] },
      { title: 'Pyogenic Granuloma', searchQuery: 'pyogenic granuloma treatment removal causes', description: 'Pyogenic granuloma guide', tags: ['Pyogenic'] },
      { title: 'Propranolol for Hemangioma', searchQuery: 'propranolol hemangioma treatment dose side effects', description: 'Propranolol therapy', tags: ['Propranolol'] },
      { title: 'Laser for Vascular Lesions', searchQuery: 'laser treatment vascular lesions pulsed dye laser', description: 'Laser therapy for vascular lesions', tags: ['Laser'] },
      { title: 'Cherry Angiomas', searchQuery: 'cherry angiomas causes treatment removal vascular', description: 'Cherry angioma overview', tags: ['Cherry'] },
      { title: 'Spider Veins', searchQuery: 'spider veins telangiectasia treatment sclerotherapy', description: 'Spider vein treatment', tags: ['Spider veins'] },
      { title: 'Kaposi Sarcoma', searchQuery: 'Kaposi sarcoma vascular tumor HIV treatment', description: 'Malignant vascular tumor', tags: ['Kaposi'] },
      { title: 'Birthmarks Overview', searchQuery: 'vascular birthmarks types treatment management', description: 'Types of vascular birthmarks', tags: ['Birthmarks'] },
    ],
  },
  {
    id: 'vasculitis',
    name: 'Vasculitis Photos',
    displayName: 'Vasculitis',
    category: 'Autoimmune',
    color: 'bg-red-700',
    youtubeSearch: 'vasculitis skin inflammation blood vessels treatment',
    videos: [
      { title: 'Cutaneous Vasculitis', searchQuery: 'cutaneous vasculitis symptoms treatment dermatology', description: 'Skin vasculitis overview', tags: ['Overview'] },
      { title: 'IgA Vasculitis', searchQuery: 'IgA vasculitis Henoch Schonlein purpura treatment', description: 'HSP vasculitis', tags: ['IgA'] },
      { title: 'Leukocytoclastic Vasculitis', searchQuery: 'leukocytoclastic vasculitis causes treatment', description: 'LCV overview', tags: ['LCV'] },
      { title: 'ANCA Vasculitis', searchQuery: 'ANCA vasculitis treatment granulomatosis', description: 'ANCA-related vasculitis', tags: ['ANCA'] },
      { title: 'Vasculitis Diagnosis', searchQuery: 'vasculitis diagnosis skin biopsy tests', description: 'How vasculitis is diagnosed', tags: ['Diagnosis'] },
      { title: 'Steroid Treatment', searchQuery: 'vasculitis corticosteroid treatment management', description: 'Treating vasculitis with steroids', tags: ['Steroids'] },
      { title: 'Livedo Reticularis', searchQuery: 'livedo reticularis causes treatment diagnosis', description: 'Net-like skin pattern', tags: ['Livedo'] },
      { title: 'Erythema Nodosum', searchQuery: 'erythema nodosum causes treatment panniculitis', description: 'Tender skin nodules', tags: ['EN'] },
      { title: 'Palpable Purpura', searchQuery: 'palpable purpura vasculitis diagnosis causes', description: 'Raised purple spots', tags: ['Purpura'] },
      { title: 'Vasculitis Management', searchQuery: 'vasculitis long term management treatment options', description: 'Long-term vasculitis care', tags: ['Management'] },
    ],
  },
  {
    id: 'chickenpox',
    name: 'Vi Chickenpox',
    displayName: 'Chickenpox',
    category: 'Viral',
    color: 'bg-sky-500',
    youtubeSearch: 'chickenpox varicella treatment prevention vaccine',
    videos: [
      { title: 'Chickenpox Overview', searchQuery: 'chickenpox varicella symptoms treatment causes', description: 'Complete chickenpox guide', tags: ['Overview'] },
      { title: 'Varicella Vaccine', searchQuery: 'varicella vaccine chickenpox why get vaccinated', description: 'Chickenpox vaccination', tags: ['Vaccine'] },
      { title: 'Chickenpox in Adults', searchQuery: 'chickenpox adults more dangerous treatment complications', description: 'Adult chickenpox risks', tags: ['Adults'] },
      { title: 'Stopping the Itch', searchQuery: 'chickenpox itch relief treatment calamine', description: 'Managing chickenpox itch', tags: ['Itch'] },
      { title: 'Chickenpox Complications', searchQuery: 'chickenpox complications pneumonia encephalitis', description: 'Serious complications', tags: ['Complications'] },
      { title: 'Acyclovir for Chickenpox', searchQuery: 'acyclovir chickenpox treatment when to use', description: 'Antiviral treatment', tags: ['Acyclovir'] },
      { title: 'Preventing Spread', searchQuery: 'chickenpox preventing spread isolation contagious', description: 'Stopping transmission', tags: ['Prevention'] },
      { title: 'Chickenpox Scars', searchQuery: 'chickenpox scar prevention treatment', description: 'Preventing and treating scars', tags: ['Scars'] },
      { title: 'Chickenpox vs Shingles', searchQuery: 'chickenpox vs shingles same virus different disease', description: 'VZV: two manifestations', tags: ['Comparison'] },
      { title: 'Immunocompromised Patients', searchQuery: 'chickenpox immunocompromised patients treatment', description: 'High-risk patients', tags: ['High-risk'] },
    ],
  },
  {
    id: 'shingles',
    name: 'Vi Shingles',
    displayName: 'Shingles (Herpes Zoster)',
    category: 'Viral',
    color: 'bg-sky-600',
    youtubeSearch: 'shingles herpes zoster treatment prevention vaccine',
    videos: [
      { title: 'Shingles Overview', searchQuery: 'shingles herpes zoster symptoms treatment causes', description: 'Complete shingles guide', tags: ['Overview'] },
      { title: 'Postherpetic Neuralgia', searchQuery: 'postherpetic neuralgia pain management treatment', description: 'Nerve pain after shingles', tags: ['PHN'] },
      { title: 'Shingles Vaccine', searchQuery: 'shingles vaccine Shingrix who needs it', description: 'Shingles vaccination guide', tags: ['Vaccine'] },
      { title: 'Antiviral Treatment', searchQuery: 'shingles antiviral treatment valacyclovir famciclovir', description: 'Antivirals for shingles', tags: ['Antivirals'] },
      { title: 'Ramsay Hunt Syndrome', searchQuery: 'Ramsay Hunt syndrome shingles ear face', description: 'Ear involvement in shingles', tags: ['RHS'] },
      { title: 'Shingles in Young Adults', searchQuery: 'shingles young adults causes stress immunosuppression', description: 'Early shingles', tags: ['Young adults'] },
      { title: 'Eye Shingles', searchQuery: 'ophthalmic herpes zoster eye shingles treatment', description: 'Shingles near the eye', tags: ['Eye'] },
      { title: 'Pain Management', searchQuery: 'shingles pain management gabapentin tricyclics', description: 'Managing shingles pain', tags: ['Pain'] },
      { title: 'Shingles Rash Care', searchQuery: 'shingles rash care wound management blisters', description: 'Caring for shingles rash', tags: ['Rash care'] },
      { title: 'Immune System & Shingles', searchQuery: 'shingles immune system reactivation stress', description: 'Why shingles reactivates', tags: ['Immune system'] },
    ],
  },
  {
    id: 'warts_viral',
    name: 'Warts Molluscum And Other Viral Infections',
    displayName: 'Warts, Molluscum & Viral',
    category: 'Viral',
    color: 'bg-sky-400',
    youtubeSearch: 'warts molluscum viral skin infection treatment',
    videos: [
      { title: 'Warts Treatment Guide', searchQuery: 'warts treatment removal dermatologist options', description: 'How to treat warts', tags: ['Warts'] },
      { title: 'Molluscum Contagiosum', searchQuery: 'molluscum contagiosum treatment children adults', description: 'Molluscum overview', tags: ['Molluscum'] },
      { title: 'Plantar Warts', searchQuery: 'plantar warts treatment removal foot dermatology', description: 'Foot warts treatment', tags: ['Plantar'] },
      { title: 'Salicylic Acid for Warts', searchQuery: 'salicylic acid warts treatment how to use', description: 'Using salicylic acid', tags: ['Salicylic acid'] },
      { title: 'Cryotherapy for Warts', searchQuery: 'cryotherapy warts liquid nitrogen treatment', description: 'Freezing warts off', tags: ['Cryotherapy'] },
      { title: 'Molluscum in Children', searchQuery: 'molluscum contagiosum children treatment watchful waiting', description: 'Managing molluscum in kids', tags: ['Children'] },
      { title: 'HPV and Warts', searchQuery: 'HPV warts common plantar flat treatment', description: 'HPV-related warts', tags: ['HPV'] },
      { title: 'Flat Warts', searchQuery: 'flat warts verruca plana treatment removal', description: 'Flat wart treatment', tags: ['Flat'] },
      { title: 'Duct Tape Method', searchQuery: 'duct tape wart removal does it work study', description: 'Home wart removal', tags: ['Home remedy'] },
      { title: 'Preventing Wart Spread', searchQuery: 'how to prevent wart spreading contagious HPV', description: 'Stopping wart transmission', tags: ['Prevention'] },
    ],
  },
  {
    id: 'benign_tumors',
    name: 'Benign',
    displayName: 'Benign Skin Tumors',
    category: 'Benign',
    color: 'bg-green-500',
    youtubeSearch: 'benign skin tumor lipoma cyst treatment dermatology',
    videos: [
      { title: 'Benign Skin Tumors Overview', searchQuery: 'benign skin tumors types overview treatment', description: 'Common benign skin growths', tags: ['Overview'] },
      { title: 'Lipomas Guide', searchQuery: 'lipoma fatty tumor causes treatment removal', description: 'Understanding lipomas', tags: ['Lipoma'] },
      { title: 'Cysts vs Lipomas', searchQuery: 'epidermoid cyst vs lipoma difference treatment', description: 'Telling them apart', tags: ['Comparison'] },
      { title: 'Epidermal Cysts', searchQuery: 'epidermal inclusion cyst treatment removal surgery', description: 'Epidermoid cysts', tags: ['Cysts'] },
      { title: 'Dermatofibromas', searchQuery: 'dermatofibroma causes treatment removal', description: 'Dermatofibroma guide', tags: ['DF'] },
      { title: 'Skin Tag Removal', searchQuery: 'skin tag removal options treatment dermatologist', description: 'Removing skin tags', tags: ['Skin tags'] },
      { title: 'Benign vs Malignant', searchQuery: 'benign vs malignant skin lesion how to tell', description: 'Recognizing worrisome lesions', tags: ['Diagnosis'] },
      { title: 'Sebaceous Cysts', searchQuery: 'sebaceous cyst treatment removal infection', description: 'Sebaceous cyst management', tags: ['Sebaceous'] },
      { title: 'Ganglion Cysts', searchQuery: 'ganglion cyst wrist treatment options', description: 'Ganglion cyst overview', tags: ['Ganglion'] },
      { title: 'When to Remove Benign Tumors', searchQuery: 'when to remove benign skin tumor indications', description: 'Deciding on removal', tags: ['Removal'] },
    ],
  },
  {
    id: 'healthy_skin',
    name: 'Heathy',
    displayName: 'Healthy Skin',
    category: 'Prevention',
    color: 'bg-green-400',
    youtubeSearch: 'healthy skin routine prevention dermatology tips',
    videos: [
      { title: 'Healthy Skin Routine', searchQuery: 'healthy skin routine dermatologist tips daily', description: 'Daily routine for skin health', tags: ['Routine'] },
      { title: 'Daily Skin Habits', searchQuery: 'daily habits healthy skin glowing tips', description: 'Best daily skin habits', tags: ['Habits'] },
      { title: 'Nutrition & Skin', searchQuery: 'nutrition healthy skin diet foods vitamins', description: 'Diet for skin health', tags: ['Nutrition'] },
      { title: 'Sleep & Skin', searchQuery: 'sleep skin health beauty sleep connection', description: 'Sleep and skin repair', tags: ['Sleep'] },
      { title: 'Hydration for Skin', searchQuery: 'hydration water skin health glow', description: 'Staying hydrated for skin', tags: ['Hydration'] },
      { title: 'Exercise & Skin', searchQuery: 'exercise skin health benefits circulation', description: 'How exercise benefits skin', tags: ['Exercise'] },
      { title: 'Sun Protection Guide', searchQuery: 'sunscreen sun protection skin cancer prevention', description: 'Protecting from sun damage', tags: ['Sun protection'] },
      { title: 'Anti-Aging Skincare', searchQuery: 'anti aging skincare evidence based retinol sunscreen', description: 'Science-backed anti-aging', tags: ['Anti-aging'] },
      { title: 'Stress & Skin', searchQuery: 'stress skin health connection management', description: 'Stress effects on skin', tags: ['Stress'] },
      { title: 'Vitamin C for Skin', searchQuery: 'vitamin C skin benefits serum how to use', description: 'Vitamin C skincare guide', tags: ['Vitamin C'] },
    ],
  },
];

export const categoryColors: Record<string, string> = {
  Inflammatory: 'bg-red-100 text-red-700',
  Bacterial: 'bg-yellow-100 text-yellow-700',
  Fungal: 'bg-teal-100 text-teal-700',
  Viral: 'bg-sky-100 text-sky-700',
  Malignant: 'bg-gray-100 text-gray-700',
  Benign: 'bg-green-100 text-green-700',
  Autoimmune: 'bg-violet-100 text-violet-700',
  Parasitic: 'bg-lime-100 text-lime-700',
  Pigmentation: 'bg-amber-100 text-amber-700',
  Vascular: 'bg-rose-100 text-rose-700',
  Systemic: 'bg-blue-100 text-blue-700',
  'Hair Disorders': 'bg-purple-100 text-purple-700',
  'Nail Disorders': 'bg-cyan-100 text-cyan-700',
  Reactive: 'bg-orange-100 text-orange-700',
  Prevention: 'bg-emerald-100 text-emerald-700',
};

export const allCategories = Array.from(new Set(diseases.map((d) => d.category)));
